pub enum rocksdb_encryption_FileEncryptionInfo {}
pub enum rocksdb_TableProperties {}
pub enum rocksdb_UserCollectedProperties {}
pub enum rocksdb_TablePropertiesCollection {}
pub enum rocksdb_FlushJobInfo {}
pub enum rocksdb_CompactionJobInfo {}
pub enum rocksdb_CompactionJobStats {}
pub enum rocksdb_SubcompactionJobInfo {}
pub enum rocksdb_ExternalFileIngestionInfo {}
pub enum rocksdb_WriteStallInfo {}
pub enum rocksdb_DBOptions {}
pub enum rocksdb_ColumnFamilyOptions {}
pub enum rocksdb_Options {}
pub enum rocksdb_titandb_TitanDBOptions {}
pub enum rocksdb_titandb_TitanCFOptions {}
pub enum rocksdb_titandb_TitanOptions {}
pub enum rocksdb_CompactionFilter_Context {}
