pub enum rocksdb_encryption_FileEncryptionInfo {}
pub enum rocksdb_TableProperties {}
pub enum rocksdb_UserCollectedProperties {}
pub enum rocksdb_TablePropertiesCollection {}
pub enum rocksdb_FlushJobInfo {}
pub enum rocksdb_CompactionJobInfo {}
pub enum rocksdb_CompactionJobStats {}
pub enum rocksdb_SubcompactionJobInfo {}
pub enum rocksdb_ExternalFileIngestionInfo {}
pub enum rocksdb_WriteStallInfo {}
pub enum rocksdb_DBOptions {}
pub enum rocksdb_ColumnFamilyOptions {}
pub enum rocksdb_Options {}
pub enum rocksdb_titandb_TitanDBOptions {}
pub enum rocksdb_titandb_TitanCFOptions {}
pub enum rocksdb_titandb_TitanOptions {}
pub enum rocksdb_CompactionFilter {}
pub enum rocksdb_CompactionFilter_Context {}
pub enum rocksdb_LRUCacheOptions {}
pub enum rocksdb_BlockBasedTableOptions {}
pub enum rocksdb_PinnableSlice {}
pub enum rocksdb_LiveFileMetaData {}
pub enum rocksdb_SstFileMetaData {}
pub enum rocksdb_LevelMetaData {}
pub enum rocksdb_ColumnFamilyMetaData {}
pub enum rocksdb_WriteBatch {}
pub enum rocksdb_PerfContext {}
pub enum rocksdb_PerfFlags {}
pub enum rocksdb_MergeOperator_MergeOperationInput {}
pub enum rocksdb_MergeOperator_MergeOperationOutput {}
pub enum rocksdb_SstFileReader {}
pub enum rocksdb_SstFileWriter {}
pub enum rocksdb_ExternalSstFileInfo {}
pub enum rocksdb_RateLimiter {}
